-- Authors
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (1, 'https://www.youtube.com/user/apfelbenny', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Benny Neugebauer', 'http://www.bennyn.de/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (2, 'https://www.youtube.com/user/tomwendelger', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Tom Wendel', 'http://tomwendelblog.wordpress.com/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (3, 'https://www.youtube.com/user/JoernLoviscach', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Prof. Dr. Jörn Loviscach', 'http://www.j3L7h.de/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (4, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Lars Vogel', 'http://www.vogella.com/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (5, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Tom Wendel & Marius Musch', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (6, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Tom Wendel, Kai Jäger & Felix Rieseberg', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (7, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Tom Wendel & Felix Rieseberg', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (8, 'http://vimeo.com/wolter', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Sascha Wolter', 'http://www.wolter.biz/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (9, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Alex Garrett', 'http://phpacademy.org/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (10, 'https://www.youtube.com/user/thenewboston', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Bucky Roberts', 'http://thenewboston.org/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (11, 'http://www.youtube.com/user/iTzAdam5X', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'iTzAdam5X', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (12, 'http://www.youtube.com/user/VISUALWORLDGmbH', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Géraud Reichert', 'http://www.visual-world.de/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (13, 'http://www.youtube.com/user/johnpapaYT', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'John Papa', 'http://www.johnpapa.net/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (14, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Adam Bien', 'http://adam-bien.tv/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (15, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Travis', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (16, 'https://www.youtube.com/user/NixiePixel', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Nixie Pixel', 'http://www.nixiepixel.com/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (17, 'https://www.youtube.com/user/wwwTheTutorialde', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Christian Simons', 'http://www.thetutorial.de/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (18, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Andy Beaulieau', 'http://www.andybeaulieu.com/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (19, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Bob Tabor', 'http://www.bobtabor.com/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (20, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Dan Fernandez', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (21, NULL, CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Rick Barraza', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (22, 'https://www.youtube.com/user/codegearguru', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Alister Christie', 'http://www.learndelphi.tv/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (23, 'https://www.youtube.com/user/theSkyLapse', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Moritz Gunz & Leo Bernard', 'http://skylapse.de/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (24, 'https://www.youtube.com/user/iBasicTutorials', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'iBasicTutorials', NULL);
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (25, 'https://www.youtube.com/user/tsjDEV86', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Thomas Sebastian Jensen', 'http://www.tsjdev.de/');
INSERT INTO `author` (`ID`,`CHANNELURL`,`CREATED`,`DESCRIPTION`,`LASTMODIFIED`,`NAME`,`WEBSITE`) VALUES (26, 'https://www.youtube.com/user/CsDoctore', CURRENT_TIMESTAMP, '', CURRENT_TIMESTAMP, 'Doctore', NULL);
-- Categories
INSERT INTO  `category` (`ID` ,`COLOR` ,`CREATED` ,`LASTMODIFIED` ,`NAME` ,`SLUG`) VALUES (NULL ,  '#123456',  '2014-02-06 00:00:00',  '2014-02-07 00:00:00','Java',  'java');